// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZAwLZTgH1CBjcq4CR2OKRS8yY-TRW48',
    appId: '1:338634852502:web:41a924474f8fa20b115ab7',
    messagingSenderId: '338634852502',
    projectId: 'hailab-polife-cheering',
    authDomain: 'hailab-polife-cheering.firebaseapp.com',
    storageBucket: 'hailab-polife-cheering.firebasestorage.app',
    measurementId: 'G-ZH6KVQQ02Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-QaY8ijdld64U33qA7bRrCldIC_bwDM',
    appId: '1:338634852502:android:00331d333d2c4323115ab7',
    messagingSenderId: '338634852502',
    projectId: 'hailab-polife-cheering',
    storageBucket: 'hailab-polife-cheering.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXvkF9zO1EKIMEWIr4jrp7CclKk97BzE',
    appId: '1:338634852502:ios:427c2ec18f7dad69115ab7',
    messagingSenderId: '338634852502',
    projectId: 'hailab-polife-cheering',
    storageBucket: 'hailab-polife-cheering.firebasestorage.app',
    iosBundleId: 'com.example.cheeringVer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXvkF9zO1EKIMEWIr4jrp7CclKk97BzE',
    appId: '1:338634852502:ios:427c2ec18f7dad69115ab7',
    messagingSenderId: '338634852502',
    projectId: 'hailab-polife-cheering',
    storageBucket: 'hailab-polife-cheering.firebasestorage.app',
    iosBundleId: 'com.example.cheeringVer1',
  );

}