// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgKbVQs8TE9NFdJhmsW01TMYUsP6RiX6k',
    appId: '1:1097783890220:android:412de73a0e482bbc691c89',
    messagingSenderId: '1097783890220',
    projectId: 'hailab-cheering',
    storageBucket: 'hailab-cheering.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI_vtM1ZK4Zi87RBsw_bkqdIV7exq7fcA',
    appId: '1:1097783890220:ios:2dda5b41305c0c0a691c89',
    messagingSenderId: '1097783890220',
    projectId: 'hailab-cheering',
    storageBucket: 'hailab-cheering.firebasestorage.app',
    iosBundleId: 'com.example.cheering',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDge4Bj5m2H9HJfOdrVjTglJbw7KRt6E',
    appId: '1:1097783890220:web:b09ea2033a7a8ea4691c89',
    messagingSenderId: '1097783890220',
    projectId: 'hailab-cheering',
    authDomain: 'hailab-cheering.firebaseapp.com',
    storageBucket: 'hailab-cheering.firebasestorage.app',
    measurementId: 'G-RNSZEELTTE',
  );

}